# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/chrony
  block:

    - name: Set OS variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"

    - name: Collecting service facts
      become: true
      ansible.builtin.service_facts:
      when:
        - "ansible_facts.services is not defined"

    - name: CIS | Ensure chrony is installed
      become: true
      ansible.builtin.package:
        name: 'chrony'
        state: present

    - name: CIS | Ensure chrony is configured
      become: true
      ansible.builtin.template:
        src: 'etc/chrony.conf.j2'
        dest: "{{ chrony_config_file }}"
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Restart chronyd'

    - name: CIS | Ensure chrony options are configured
      become: true
      ansible.builtin.template:
        src: 'etc/sysconfig/chronyd.j2'
        dest: '/etc/sysconfig/chronyd'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when:
        - ansible_os_family == "RedHat"
      notify:
        - 'Restart chronyd'

    - name: CIS | Ensure chrony keys are configured
      become: true
      ansible.builtin.template:
        src: 'etc/chrony.keys.j2'
        dest: "{{ chrony_keys_file }}"
        owner: 'root'
        group: "{{ chrony_group }}"
        mode: '0640'
      notify:
        - 'Restart chronyd'

    - name: Create chronyd service override directory
      become: true
      ansible.builtin.file:
        name: '/etc/systemd/system/chronyd.service.d'
        state: directory
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: Fix umask for chronyd
      become: true
      ansible.builtin.template:
        src: 'etc/systemd/system/chronyd.service.d/override.conf.j2'
        dest: '/etc/systemd/system/chronyd.service.d/override.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Systemd daemon-reload'
        - 'Restart chronyd'
        - 'Sync time'

    - name: CIS | Ensure systemd-timesyncd is disabled (systemd)
      become: true
      ansible.builtin.systemd:
        name: 'systemd-timesyncd.service'
        masked: true
        enabled: false
        state: stopped
      when:
        - "'systemd-timesyncd' in ansible_facts.services"

    # The Debian CIS-CAT audit still looks for the symlink showing
    # that systemd-timesyncd is masked, even when systemd-timesyncd
    # is not installed.  This command creates the symlink and allows
    # the CIS-CAT audit to pass.
    - name: CIS | Ensure systemd-timesyncd is disabled (cmd)  # noqa: command-instead-of-module
      become: true
      ansible.builtin.command:
        cmd: 'systemctl --now mask systemd-timesyncd'
      when:
        - ansible_os_family|lower == 'debian'
        - "'systemd-timesyncd' not in ansible_facts.services"

    - name: CIS | Ensure ntp is removed
      become: true
      ansible.builtin.package:
        name: 'ntp'
        state: absent

    # Flush any handlers that we might have called
    - name: Flush handlers
      ansible.builtin.meta:
        flush_handlers

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_chrony'
